    push:
    schedule:
    - cron: '0 */6 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 22
        - timeout-minutes: 355
          run: |
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timebuckwall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timewall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/alexamaster.mjs
              git add timebuckwall.mjs timewall.mjs alexamaster.mjs
              git config user.name dummy
              git config user.email dummy
              git commit --allow-empty-message -m '' || true
              git push
              sudo apt update
              sudo apt install -y --no-install-recommends node-commander lxde
              mkdir ~/.ssh/
              echo '${{secrets.id_rsa}}' > ~/.ssh/id_rsa
              chmod 400 ~/.ssh/id_rsa
              npm install playwright-chromium@1.40.0 lodash-es canvas@next jsdom sqlite3 sqlite ssh2-promise html-entities tough-cookie unraw ioredis json5 git+https://github.com/fancy45daddy/tlsclient.js --force
              awk -i inplace '/^import /{seen++} seen && !/^import /{print "import formDataToStream from \x27./helpers/formDataToStream.js\x27;"; seen=0}1' $(npm root)/axios/lib/axios.js
              awk -i inplace '!found && /axios.default/ {print "axios.formDataToStream = formDataToStream;"; found=1}1' $(npm root)/axios/lib/axios.js
              #node alexamaster.mjs &
              Xvfb :99 &
              DISPLAY=:99 node timebuckwall.mjs --browserstackName ${{secrets.browserstackName}} --browserstackKey ${{secrets.browserstackKey}} --gemini ${{secrets.gemini}} --redis ${{secrets.redis}} &
              node timewall.mjs --redis ${{secrets.redis}}
    time:
        runs-on: ubuntu-latest
        env:
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        strategy:
            fail-fast: false
            matrix:
                ip: [192.9.225.198, 52.167.216.190, 155.248.201.240]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 22
        - timeout-minutes: 355
          run: |
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timebuckwall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timewall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/alexamaster.mjs
              podman run -d -e RP_EMAIL=chaowen.guo1@gmail.com -e RP_API_KEY=9b23ebb9-2ee1-427f-a271-f6fdf536537b docker.io/repocket/repocket
              sudo apt update
              sudo apt install -y --no-install-recommends node-commander lxde
              mkdir ~/.ssh/
              echo '${{secrets.id_ed25519}}' > ~/.ssh/id_ed25519
              chmod 400 ~/.ssh/id_ed25519
              npm install playwright-chromium@1.40.0 lodash-es canvas@next jsdom sqlite3 sqlite ssh2-promise html-entities tough-cookie unraw ioredis json5 git+https://github.com/fancy45daddy/tlsclient.js --force
              awk -i inplace '/^import /{seen++} seen && !/^import /{print "import formDataToStream from \x27./helpers/formDataToStream.js\x27;"; seen=0}1' $(npm root)/axios/lib/axios.js
              awk -i inplace '!found && /axios.default/ {print "axios.formDataToStream = formDataToStream;"; found=1}1' $(npm root)/axios/lib/axios.js
              #node alexamaster.mjs &
              Xvfb :99 &
              DISPLAY=:99 node timebuckwall.mjs --browserstackName ${{secrets.browserstackName}} --browserstackKey ${{secrets.browserstackKey}} --gemini ${{secrets.gemini}} --redis ${{secrets.redis}} --ip ${{matrix.ip}} &
              node timewall.mjs --redis ${{secrets.redis}} --ip ${{matrix.ip}}
    next:
        runs-on: ubuntu-latest
        env:
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        strategy:
            fail-fast: false
            matrix:
                ip: [52.167.216.178, 146.235.194.203, 13.89.100.0, 104.42.130.173]
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 22
        - timeout-minutes: 355
          run: |
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timebuckwall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/timewall.mjs
              curl -O https://dev.azure.com/chaowenguo/ci/_apis/git/repositories/ci/items?path=/alexamaster.mjs
              if [ ${matrix.ip} == 52.167.216.178 ]
              then
                  git add timebuckwall.mjs timewall.mjs alexamaster.mjs
                  git config user.name dummy
                  git config user.email dummy
                  git commit --allow-empty-message -m '' || true
                  git push
              fi
              podman run -d -e RP_EMAIL=chaowen.guo1@gmail.com -e RP_API_KEY=9b23ebb9-2ee1-427f-a271-f6fdf536537b docker.io/repocket/repocket
              sudo apt update
              sudo apt install -y --no-install-recommends node-commander lxde
              mkdir ~/.ssh/
              echo '${{secrets.id_ed25519}}' > ~/.ssh/id_ed25519
              chmod 400 ~/.ssh/id_ed25519
              npm install playwright-chromium@1.40.0 lodash-es canvas@next jsdom sqlite3 sqlite ssh2-promise html-entities tough-cookie unraw ioredis json5 git+https://github.com/fancy45daddy/tlsclient.js --force
              awk -i inplace '/^import /{seen++} seen && !/^import /{print "import formDataToStream from \x27./helpers/formDataToStream.js\x27;"; seen=0}1' $(npm root)/axios/lib/axios.js
              awk -i inplace '!found && /axios.default/ {print "axios.formDataToStream = formDataToStream;"; found=1}1' $(npm root)/axios/lib/axios.js
              #node alexamaster.mjs &
              Xvfb :99 &
              DISPLAY=:99 node timebuckwall.mjs --browserstackName ${{secrets.browserstackName}} --browserstackKey ${{secrets.browserstackKey}} --gemini ${{secrets.gemini}} --redis ${{secrets.redis}} --ip ${{matrix.ip}} &
              node timewall.mjs --redis ${{secrets.redis}} --ip ${{matrix.ip}}
    #clean:
    #    runs-on: ubuntu-latest
    #    permissions:
    #        actions: write
    #    steps:
    #    - run: |
    #          sudo apt update
    #          sudo apt install -y --no-install-recommends python3-aiohttp
    #          curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python3 - ${{secrets.GITHUB_TOKEN}}
